# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWindow(object):
    def setupUi(self, GeneratorWindow):
        GeneratorWindow.setObjectName("GeneratorWindow")
        GeneratorWindow.resize(944, 600)
        self.centralwidget = QtWidgets.QWidget(GeneratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 40, 341, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(20, 30, 301, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.poisson_radioButton = QtWidgets.QRadioButton(self.frame)
        self.poisson_radioButton.setGeometry(QtCore.QRect(20, 10, 82, 17))
        self.poisson_radioButton.setObjectName("poisson_radioButton")
        self.exponencial_radioButton = QtWidgets.QRadioButton(self.frame)
        self.exponencial_radioButton.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.exponencial_radioButton.setObjectName("exponencial_radioButton")
        self.calculate_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.calculate_pushButton.setGeometry(QtCore.QRect(20, 350, 75, 23))
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.pdf_export_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pdf_export_pushButton.setGeometry(QtCore.QRect(110, 350, 75, 23))
        self.pdf_export_pushButton.setObjectName("pdf_export_pushButton")
        self.clean_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.clean_pushButton.setGeometry(QtCore.QRect(200, 350, 75, 23))
        self.clean_pushButton.setObjectName("clean_pushButton")
        self.lambda_label = QtWidgets.QLabel(self.frame_2)
        self.lambda_label.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.lambda_label.setObjectName("lambda_label")
        self.variables_amount_label = QtWidgets.QLabel(self.frame_2)
        self.variables_amount_label.setGeometry(QtCore.QRect(10, 200, 111, 16))
        self.variables_amount_label.setObjectName("variables_amount_label")
        self.random_numbers_amount_label = QtWidgets.QLabel(self.frame_2)
        self.random_numbers_amount_label.setGeometry(QtCore.QRect(10, 230, 161, 16))
        self.random_numbers_amount_label.setObjectName("random_numbers_amount_label")
        self.lambda_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lambda_input_lineEdit.setGeometry(QtCore.QRect(190, 170, 113, 20))
        self.lambda_input_lineEdit.setObjectName("lambda_input_lineEdit")
        self.variables_amount_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.variables_amount_input_lineEdit.setGeometry(QtCore.QRect(190, 200, 113, 20))
        self.variables_amount_input_lineEdit.setObjectName("variables_amount_input_lineEdit")
        self.random_numbers_amount_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.random_numbers_amount_input_lineEdit.setGeometry(QtCore.QRect(190, 230, 113, 20))
        self.random_numbers_amount_input_lineEdit.setObjectName("random_numbers_amount_input_lineEdit")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(380, 40, 541, 501))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.database_tableView = QtWidgets.QTableWidget(self.frame_3)
        self.database_tableView.setGeometry(QtCore.QRect(20, 10, 511, 481))
        self.database_tableView.setObjectName("database_tableView")
        self.database_tableView.setColumnCount(0)
        self.database_tableView.setRowCount(0)
        self.open_reports_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_reports_pushButton.setGeometry(QtCore.QRect(810, 10, 75, 23))
        self.open_reports_pushButton.setObjectName("open_reports_pushButton")
        GeneratorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 21))
        self.menubar.setObjectName("menubar")
        GeneratorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GeneratorWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWindow)

    def retranslateUi(self, GeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorWindow.setWindowTitle(_translate("GeneratorWindow", "MainWindow"))
        self.poisson_radioButton.setText(_translate("GeneratorWindow", "Poisson"))
        self.exponencial_radioButton.setText(_translate("GeneratorWindow", "exponencial"))
        self.calculate_pushButton.setText(_translate("GeneratorWindow", "Calcular"))
        self.pdf_export_pushButton.setText(_translate("GeneratorWindow", "Exportar"))
        self.clean_pushButton.setText(_translate("GeneratorWindow", "Limpiar"))
        self.lambda_label.setText(_translate("GeneratorWindow", "lambda"))
        self.variables_amount_label.setText(_translate("GeneratorWindow", "Numeros de variables"))
        self.random_numbers_amount_label.setText(_translate("GeneratorWindow", "Cantidad de numeros aleatorios"))
        self.open_reports_pushButton.setText(_translate("GeneratorWindow", "Abril reportes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneratorWindow = QtWidgets.QMainWindow()
    ui = Ui_GeneratorWindow()
    ui.setupUi(GeneratorWindow)
    GeneratorWindow.show()
    sys.exit(app.exec_())
