# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWindow(object):
    def setupUi(self, GeneratorWindow):
        GeneratorWindow.setObjectName("GeneratorWindow")
        GeneratorWindow.resize(941, 620)
        self.centralwidget = QtWidgets.QWidget(GeneratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 90, 391, 501))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #007bff;\n"
"border-radius:5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(40, 110, 311, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.poisson_radioButton = QtWidgets.QRadioButton(self.frame)
        self.poisson_radioButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.poisson_radioButton.setFont(font)
        self.poisson_radioButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.poisson_radioButton.setObjectName("poisson_radioButton")
        self.exponencial_radioButton = QtWidgets.QRadioButton(self.frame)
        self.exponencial_radioButton.setGeometry(QtCore.QRect(180, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exponencial_radioButton.setFont(font)
        self.exponencial_radioButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"padding: 2px;")
        self.exponencial_radioButton.setObjectName("exponencial_radioButton")
        self.calculate_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.calculate_pushButton.setGeometry(QtCore.QRect(20, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.calculate_pushButton.setFont(font)
        self.calculate_pushButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"\n"
"border: none;")
        self.calculate_pushButton.setCheckable(False)
        self.calculate_pushButton.setAutoDefault(False)
        self.calculate_pushButton.setFlat(False)
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        self.pdf_export_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pdf_export_pushButton.setGeometry(QtCore.QRect(150, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pdf_export_pushButton.setFont(font)
        self.pdf_export_pushButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"\n"
"border: none;")
        self.pdf_export_pushButton.setObjectName("pdf_export_pushButton")
        self.clean_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.clean_pushButton.setGeometry(QtCore.QRect(280, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clean_pushButton.setFont(font)
        self.clean_pushButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"\n"
"border: none;")
        self.clean_pushButton.setObjectName("clean_pushButton")
        self.lambda_label = QtWidgets.QLabel(self.frame_2)
        self.lambda_label.setGeometry(QtCore.QRect(20, 190, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lambda_label.setFont(font)
        self.lambda_label.setStyleSheet("border: 1px solid #007bff;")
        self.lambda_label.setObjectName("lambda_label")
        self.variables_amount_label = QtWidgets.QLabel(self.frame_2)
        self.variables_amount_label.setGeometry(QtCore.QRect(20, 250, 191, 20))
        self.variables_amount_label.setStyleSheet("border: 1px solid #007bff;\n"
"")
        self.variables_amount_label.setObjectName("variables_amount_label")
        self.random_numbers_amount_label = QtWidgets.QLabel(self.frame_2)
        self.random_numbers_amount_label.setGeometry(QtCore.QRect(20, 310, 191, 20))
        self.random_numbers_amount_label.setStyleSheet("border: 1px solid #007bff;\n"
"")
        self.random_numbers_amount_label.setObjectName("random_numbers_amount_label")
        self.lambda_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lambda_input_lineEdit.setGeometry(QtCore.QRect(240, 190, 113, 20))
        self.lambda_input_lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 1px solid #cccccc;")
        self.lambda_input_lineEdit.setObjectName("lambda_input_lineEdit")
        self.variables_amount_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.variables_amount_input_lineEdit.setGeometry(QtCore.QRect(240, 250, 113, 20))
        self.variables_amount_input_lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 1px solid #cccccc;")
        self.variables_amount_input_lineEdit.setObjectName("variables_amount_input_lineEdit")
        self.random_numbers_amount_input_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.random_numbers_amount_input_lineEdit.setGeometry(QtCore.QRect(240, 310, 113, 20))
        self.random_numbers_amount_input_lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border: 1px solid #cccccc;")
        self.random_numbers_amount_input_lineEdit.setObjectName("random_numbers_amount_input_lineEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"padding: 16px;")
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(410, 90, 521, 501))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #007bff;\n"
"border-radius:5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.database_tableView = QtWidgets.QTableWidget(self.frame_3)
        self.database_tableView.setGeometry(QtCore.QRect(10, 10, 501, 341))
        self.database_tableView.setMaximumSize(QtCore.QSize(511, 481))
        self.database_tableView.setObjectName("database_tableView")
        self.database_tableView.setColumnCount(0)
        self.database_tableView.setRowCount(0)
        self.statistics_tableView = QtWidgets.QTableWidget(self.frame_3)
        self.statistics_tableView.setGeometry(QtCore.QRect(10, 360, 501, 131))
        self.statistics_tableView.setObjectName("statistics_tableView")
        self.statistics_tableView.setColumnCount(0)
        self.statistics_tableView.setRowCount(0)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #007bff;\n"
"border-radius:5px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(70, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setObjectName("label_5")
        self.open_reports_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.open_reports_pushButton.setGeometry(QtCore.QRect(800, 20, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.open_reports_pushButton.setFont(font)
        self.open_reports_pushButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"\n"
"border: none;")
        self.open_reports_pushButton.setObjectName("open_reports_pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/prefijoNuevo/wind.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.open_manual_pushButton = QtWidgets.QPushButton(self.frame_5)
        self.open_manual_pushButton.setGeometry(QtCore.QRect(680, 20, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.open_manual_pushButton.setFont(font)
        self.open_manual_pushButton.setStyleSheet("background-color: #007bff;\n"
"color: #ffffff;\n"
"border-radius: 4px;\n"
"\n"
"border: none;")
        self.open_manual_pushButton.setObjectName("open_manual_pushButton")
        self.frame_5.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        GeneratorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GeneratorWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GeneratorWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWindow)

    def retranslateUi(self, GeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorWindow.setWindowTitle(_translate("GeneratorWindow", "MainWindow"))
        self.poisson_radioButton.setText(_translate("GeneratorWindow", "Poisson"))
        self.exponencial_radioButton.setText(_translate("GeneratorWindow", "Exponencial"))
        self.calculate_pushButton.setText(_translate("GeneratorWindow", "Calcular"))
        self.pdf_export_pushButton.setText(_translate("GeneratorWindow", "Exportar"))
        self.clean_pushButton.setText(_translate("GeneratorWindow", "Limpiar"))
        self.lambda_label.setText(_translate("GeneratorWindow", "Lambda (λ)"))
        self.variables_amount_label.setText(_translate("GeneratorWindow", "Numeros de variables"))
        self.random_numbers_amount_label.setText(_translate("GeneratorWindow", "Cantidad de numeros aleatorios"))
        self.label.setText(_translate("GeneratorWindow", "  Generador de numeros aleatorios"))
        self.label_5.setText(_translate("GeneratorWindow", "LineFlow"))
        self.open_reports_pushButton.setText(_translate("GeneratorWindow", "Abrir reportes"))
        self.open_manual_pushButton.setText(_translate("GeneratorWindow", "Manual"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneratorWindow = QtWidgets.QMainWindow()
    ui = Ui_GeneratorWindow()
    ui.setupUi(GeneratorWindow)
    GeneratorWindow.show()
    sys.exit(app.exec_())
